# Generated by Django 6.1 on 2026-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='نام انگلیسی')),
                ('name_fa', models.CharField(max_length=100, verbose_name='نام فارسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی اتاق',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اتاق',
            },
        ),
    ]
