# Generated by Django 6.1 on 2026-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام امکان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'امکان اتاق',
                'verbose_name_plural': 'امکانات اتاق',
            },
        ),
    ]
