# Generated by Django 6.1 on 2026-08-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اتاق')),
                ('code', models.CharField(editable=False, max_length=4, unique=True, verbose_name='کد اتاق')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('features', models.TextField(blank=True, help_text='هر ویژگی را در یک خط بنویسید', verbose_name='ویژگی\u200cهای اتاق')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت هر شب (تومان)')),
                ('quantity', models.PositiveSmallIntegerField(default=2, verbose_name='موجودی')),
                ('capacity_label', models.CharField(blank=True, max_length=50, verbose_name='ظرفیت (متنی)')),
                ('size_sqm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='متراژ (متر مربع)')),
                ('bed_type', models.CharField(blank=True, max_length=100, verbose_name='نوع تخت')),
                ('view_type', models.CharField(blank=True, max_length=100, verbose_name='نوع چشم\u200cانداز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity', verbose_name='امکانات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='rooms.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'نوع اتاق',
                'verbose_name_plural': 'انواع اتاق',
            },
        ),
    ]
