# Generated by Django 6.1 on 2026-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه'),
        ),
    ]
