# Generated by Django 6.1 on 2026-08-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('restaurant', 'رستوران'), ('cafe', 'کافه'), ('pool', 'استخر'), ('massage', 'ماساژ')], max_length=20, verbose_name='نوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'امکان نمایشی',
                'verbose_name_plural': 'امکانات نمایشی',
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facilities/', verbose_name='تصویر')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.facility', verbose_name='امکان')),
            ],
            options={
                'verbose_name': 'تصویر امکان',
                'verbose_name_plural': 'تصاویر امکانات',
            },
        ),
    ]
