# Generated by Django 6.1 on 2026-08-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار و رویدادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
