# Generated by Django 6.1 on 2026-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('restaurant', 'رستوران'), ('cafe', 'کافه')], max_length=20, verbose_name='نوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام سالن')),
                ('image', models.ImageField(upload_to='halls/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'سالن',
                'verbose_name_plural': 'سالن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('restaurant', 'رستوران'), ('cafe', 'کافه')], max_length=20, verbose_name='نوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام آیتم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
            },
        ),
        migrations.RemoveField(
            model_name='facilityimage',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityImage',
        ),
    ]
