# Generated by Django 6.1 on 2026-08-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hall_menuitem_remove_facilityimage_facility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='massage/', verbose_name='تصویر')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'خدمت ماساژ',
                'verbose_name_plural': 'خدمات ماساژ',
            },
        ),
        migrations.AlterField(
            model_name='hall',
            name='facility_type',
            field=models.CharField(choices=[('restaurant', 'رستوران'), ('cafe', 'کافه'), ('massage', 'ماساژ')], max_length=20, verbose_name='نوع'),
        ),
    ]
