# Generated by Django 6.1 on 2026-08-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='تصویر'),
        ),
    ]
