# Generated by Django 6.1 on 2026-08-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='pool/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
            ],
            options={
                'verbose_name': 'ویژگی استخر',
                'verbose_name_plural': 'استخر (ویژگی\u200cها)',
            },
        ),
    ]
