# Generated by Django 6.1 on 2026-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_poolfeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار و رویدادها'},
        ),
        migrations.AlterModelOptions(
            name='poolfeature',
            options={'ordering': ['order'], 'verbose_name': 'ویژگی استخر', 'verbose_name_plural': 'استخر (ویژگی\u200cها)'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='poolfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
