# Generated by Django 6.1 on 2026-08-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_news_options_alter_poolfeature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'آیتم منو', 'verbose_name_plural': 'آیتم\u200cهای منو'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
