# Generated by Django 6.1 on 2026-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_menuitem_options_menuitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ['order'], 'verbose_name': 'سالن', 'verbose_name_plural': 'سالن\u200cها'},
        ),
        migrations.AddField(
            model_name='hall',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
