# Generated by Django 6.1 on 2026-08-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_hall_options_hall_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massageservice',
            options={'ordering': ['order'], 'verbose_name': 'خدمت ماساژ', 'verbose_name_plural': 'خدمات ماساژ'},
        ),
        migrations.AddField(
            model_name='massageservice',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
