# Generated by Django 6.1 on 2026-08-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0004_roomimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='تاریخ ورود')),
                ('check_out', models.DateField(verbose_name='تاریخ خروج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت رزرو')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('delivered', 'تحویل گرفته شده'), ('checked_out', 'تخلیه شده'), ('cancelled', 'کنسل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('confirmation_code', models.CharField(editable=False, max_length=5, unique=True, verbose_name='کد تأیید')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.roomtype', verbose_name='نوع اتاق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.reservation', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'مهمان رزرو',
                'verbose_name_plural': 'مهمانان رزرو',
            },
        ),
    ]
