# Generated by Django 6.1 on 2026-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأییدشده'), ('delivered', 'تحویل\u200cشده'), ('checked_out', 'تسویه\u200cشده'), ('cancelled', 'لغوشده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
