# Generated by Django 6.1 on 2026-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='عکس پروفایل')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('role', models.CharField(choices=[('normal', 'کاربر عادی'), ('admin_main', 'ادمین اصلی'), ('admin_reservation', 'ادمین رزرواسیون')], default='normal', max_length=20, verbose_name='نقش')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='شماره تأیید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی پنل ادمین جنگو')),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق ورود')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='قفل تا')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='یادداشت داخلی ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
